### PR TITLE
Fix compilation faults when installing in HA OS

### LINKED ISSUE #9: Can't install pwmled in Homeassitant Operating system
Since Homeassistant Operating system (HA OS) is using python 3.10 it uses musllinux wheels (explanation: https://github.com/home-assistant/core/issues/75672#issuecomment-1193184688). So if you install a component with pwmled as requirement, you can't use 2022.7+ because it will try to find muslinux wheels, and if it can't, it will try to build from source (which fails). More information can be found also in this issue description: https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/issues/9

For this reasons, the https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM repro has moved to the use of gpiozero instead of pwmled. However, they lost support for the pca9685, as well as for transitions and RGB/RGBW Leds by that move. <del>It would be nicer if we change the gpio driver of pwmled to work via gpiozero, so that the compilation step is no longer required. 
Do you support it if I move from pippio to the gpiozero driver?</del>

After some fiddling around, it was shown that just updating the version numbers of the dependent packages plus adding RPi.GPIO will fix this issue. A temporary test version of this package is available at https://pypi.org/project/pwmled-ant/.

### PR DESCRIPTION
**Pull request by antonverburg**
This will fix https://github.com/soldag/python-pwmled/issues/9

### CODE REVIEW

**Comment by antonverburg** [comment]
After pulling this you can create a new package with `python3 -m build`. Upload the pip package to pip with `twine upload dist/*`.

**Comment by antonverburg** [comment]
Has been tested with https://pypi.org/project/pwmled-ant/ and https://github.com/antonverburg/ha-pca9685/ under HA OS and seems to work fine.

**Comment by soldag** [comment]
Thanks for your investigation and contribution. I would like to keep poetry as build tool. If updating adafruit-blinka to 8.21 fixes the issue please just bump the corresponding version constraint from `>=5.5.1,<8.0` to `>=5.5.1,<9.0`. 

You also added RPi.GPIO to the project. Why is that needed? It's not used by this lib.

**Comment by antonverburg** [comment]
RPi.GPIO is added because if I did not add it HA OS was complaining that it missed the RPi.GPIO. If you like it I can also add it to the requirements of the integration that I created. If I have some time I will create & test a package with poetry.

**Comment by soldag** [comment]
Ok weird. Do you have the stacktrace of that error?

Just because I'm using poetry doesn't mean that you need to use it as well. I'll push the package to the PyPI registry and you can use whatever tool you like to install it from there.

**Comment by antonverburg** [comment]
Don't have a stacktrace, but I am sure I can reproduce it. But it might be better if you do not include the dependency in your package; as long as a user only uses the PCA9685 part RPi.GPIO is not required for sure. And if a user only uses it remote, I am not sure as well if it's required. I can put the dependency in per package, for example the [ha_pca9585 integration](https://github.com/antonverburg/ha-pca9685) should not need it.

**Comment by antonverburg** [comment]
I was busy for a while with some other things, here is the poetry variant. Can you please build a new package with it?

**Comment by antonverburg** [comment]
This is the fault that I get when RPi.GPIO is not installed:

```
File "/home/homeassistant/.homeassistant/custom_components/pca9685/light.py", line 5, in <module>
    from pwmled.driver.pca9685 import Pca9685Driver
  File "/home/homeassistant/homeassistant-core/venv/lib/python3.11/site-packages/pwmled/driver/pca9685.py", line 6, in <module>
    import board
  File "/home/homeassistant/homeassistant-core/venv/lib/python3.11/site-packages/board.py", line 47, in <module>
    from adafruit_blinka.board.raspberrypi.raspi_40pin import *
  File "/home/homeassistant/homeassistant-core/venv/lib/python3.11/site-packages/adafruit_blinka/board/raspberrypi/raspi_40pin.py", line 6, in <module>
    from adafruit_blinka.microcontroller.bcm283x import pin
  File "/home/homeassistant/homeassistant-core/venv/lib/python3.11/site-packages/adafruit_blinka/microcontroller/bcm283x/pin.py", line 5, in <module>
    from RPi import GPIO
  File "/home/homeassistant/homeassistant-core/venv/lib/python3.11/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by /home/homeassistant/homeassistant-core/venv/lib/python3.11/site-packages/RPi/_GPIO.cpython-311-arm-linux-gnueabihf.so)
```

**Comment by antonverburg** [comment]
Seems pca9685.py driver uses generic 'board'  definition to define SCL and SCA pins. For this definition the RPi.GPIO is required.

**Comment by soldag** [comment]
Thanks. I by accident pushed your commit directly without merging this PR 🤦  Anyway, it's released now. I might look into the issue with RPi.GPIO, when I have some time. Thanks for the details

**Pull request closed without merging**
